# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prompt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.promptNameInput = QtWidgets.QLineEdit(Form)
        self.promptNameInput.setObjectName("promptNameInput")
        self.verticalLayout.addWidget(self.promptNameInput)
        self.promptInput = QtWidgets.QTextEdit(Form)
        self.promptInput.setObjectName("promptInput")
        self.verticalLayout.addWidget(self.promptInput)
        self.targetFieldInput = QtWidgets.QLineEdit(Form)
        self.targetFieldInput.setObjectName("targetFieldInput")
        self.verticalLayout.addWidget(self.targetFieldInput)
        self.removePromptButton = QtWidgets.QToolButton(Form)
        self.removePromptButton.setObjectName("removePromptButton")
        self.verticalLayout.addWidget(self.removePromptButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.promptNameInput.setPlaceholderText(_translate("Form", "Prompt Name"))
        self.promptInput.setPlaceholderText(_translate("Form", "Prompt"))
        self.targetFieldInput.setPlaceholderText(_translate("Form", "Target Field"))
        self.removePromptButton.setToolTip(_translate("Form", "Remove this prompt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
